"use client";

import Link from "next/link";
import { FiChevronLeft, FiDownload, FiFileText } from "react-icons/fi";

export default function ReportResult() {
  const rows = [
    { number: "ST-1023", agent: "Donna Cozart", date: "Oct 01", total: "$5,300" },
    { number: "ST-1023", agent: "Frank Wang", date: "Sep 01", total: "$5,300" },
    { number: "ST-1023", agent: "Donna Cozart", date: "Jun 01", total: "$5,300" },
    { number: "ST-1023", agent: "Frank Wang", date: "Aug 01", total: "$5,300" },
  ];

  return (
    <div className="min-h-screen px-6 py-6">
      <div className="">

        {/* TOP BAR */}
        <div className="flex items-center justify-between mb-4">
          <div>
            <div className="flex items-center gap-3">
              <Link href="/reports">
              <button className="w-8 h-8 rounded-full bg-white border border-gray-200 flex items-center justify-center shadow-sm">
                <FiChevronLeft className="text-gray-600 text-[16px]" />
              </button>
              </Link>
              <h1 className="text-[18px] font-semibold text-[#111827]">Report Result</h1>
            </div>

            <p className="text-[12px] text-gray-500 mt-1 ml-11">
              Statements Report — 2025-10-17 - 2025-10-22
            </p>
          </div>

          {/* RIGHT BUTTONS */}
          <div className="flex items-center gap-2">
            <TopBtn icon={<FiDownload />} label="Download" />
            <TopBtn icon={<FiFileText />} label="Export PDF" />
            <TopBtn icon={<FiFileText />} label="Export CSV" />
          </div>
        </div>

        {/* FILTERS CARD */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5 mb-5">
          <h2 className="text-[14px] font-semibold mb-4 text-gray-800">Report Filters</h2>

          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-y-3 gap-x-8 text-[13px]">
            <FilterItem label="Report Type" value="Statements" />
            <FilterItem label="Statements" value="Donna Cozart" />
            <FilterItem label="Generated By" value="Admin" />
            <FilterItem label="Generated On" value="October 10, 2025 at 03:18 PM" />
            <FilterItem label="Format" value="PDF" />
          </div>
        </div>

        {/* SUMMARY STRIP */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5 mb-5">
          <h2 className="text-[14px] font-semibold mb-4 text-gray-800">Summary</h2>

          <div className="grid grid-cols-1 sm:grid-cols-5 gap-3 text-[13px]">
            <SummaryCard value="5" label="Total Records" bg="bg-[#E9D8FD]" color="text-[#4C1D95]" />
            <SummaryCard value="$23,210" label="Total Amount" bg="bg-[#DBEAFE]" color="text-[#1D4ED8]" />
            <SummaryCard value="3" label="Approved" bg="bg-[#DCFCE7]" color="text-[#15803D]" />
            <SummaryCard value="1" label="Pending" bg="bg-[#FEF3C7]" color="text-[#92400E]" />
            <SummaryCard value="1" label="Rejected" bg="bg-[#FEE2E2]" color="text-[#B91C1C]" />
          </div>
        </div>

        {/* RECENT DATA TABLE */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm">
          <div className="px-5 pt-4 pb-3 border-b border-gray-200">
            <h2 className="text-[14px] font-semibold text-gray-800">Recent Data</h2>
          </div>

          {/* HEADER */}
          <div className="bg-[#F7FAFD] grid grid-cols-4 px-5 py-3 text-[12px] font-medium text-gray-500 border-b border-gray-200 rounded-t-none">
            <div>STATEMENT NUMBER</div>
            <div>AGENT</div>
            <div>DATE</div>
            <div>TOTAL</div>
          </div>

          {/* ROWS */}
          <div>
            {rows.map((row, index) => (
              <div
                key={index}
                className="grid grid-cols-4 px-5 py-3 text-[14px] text-gray-800 border-b border-gray-100 hover:bg-gray-50"
              >
                <div>{row.number}</div>
                <div>{row.agent}</div>
                <div>{row.date}</div>
                <div>{row.total}</div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
}

/* ---------------- SMALL COMPONENTS ---------------- */

function TopBtn({ icon, label }) {
  return (
    <button className="flex items-center gap-2 px-4 py-2 bg-[#2199E8] text-white text-[13px] rounded-[8px] shadow-sm hover:bg-[#1b86c7] transition">
      <span className="text-[16px]">{icon}</span>
      {label}
    </button>
  );
}

function FilterItem({ label, value }) {
  return (
    <div>
      <p className="text-[12px] text-gray-500 mb-1">{label}</p>
      <p className="text-[13px] font-medium text-gray-800">{value}</p>
    </div>
  );
}

function SummaryCard({ value, label, bg, color }) {
  return (
    <div className={`${bg} rounded-lg px-4 py-3 flex flex-col justify-center`}>
      <p className={`text-[18px] font-semibold ${color}`}>{value}</p>
      <p className="text-[12px] text-gray-600 mt-1">{label}</p>
    </div>
  );
}
